[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
calculator_program = "2aoPWftL1dCpAJwVh5TwAeqJ7jaBTNjN7fDigJ9uvW8r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/johnivanpuayap/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
